// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmhk25Bnv-elYKqdb_iNKHvZeqq0fH5Lo',
    appId: '1:129544519291:web:93cc71e06fcfa8aba2ecde',
    messagingSenderId: '129544519291',
    projectId: 'barbaer-shop',
    authDomain: 'barbaer-shop.firebaseapp.com',
    storageBucket: 'barbaer-shop.firebasestorage.app',
    measurementId: 'G-BM21JWM8XY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArZTtat5mwIvNzp3kqnevlai5jaENdyCg',
    appId: '1:129544519291:android:330e138ec29853b9a2ecde',
    messagingSenderId: '129544519291',
    projectId: 'barbaer-shop',
    storageBucket: 'barbaer-shop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG1LJR-T-wybA0HSdBG20t0Alr19hE9gc',
    appId: '1:129544519291:ios:18209d86b343b663a2ecde',
    messagingSenderId: '129544519291',
    projectId: 'barbaer-shop',
    storageBucket: 'barbaer-shop.firebasestorage.app',
    iosBundleId: 'com.example.barberShopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG1LJR-T-wybA0HSdBG20t0Alr19hE9gc',
    appId: '1:129544519291:ios:18209d86b343b663a2ecde',
    messagingSenderId: '129544519291',
    projectId: 'barbaer-shop',
    storageBucket: 'barbaer-shop.firebasestorage.app',
    iosBundleId: 'com.example.barberShopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmhk25Bnv-elYKqdb_iNKHvZeqq0fH5Lo',
    appId: '1:129544519291:web:9aab3e3e87e40530a2ecde',
    messagingSenderId: '129544519291',
    projectId: 'barbaer-shop',
    authDomain: 'barbaer-shop.firebaseapp.com',
    storageBucket: 'barbaer-shop.firebasestorage.app',
    measurementId: 'G-M558410Y1V',
  );
}
